apiVersion: v1
kind: Service
metadata:
  labels:
    name: bank-service 
  name: bank-service   
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8458
  selector:
    app: bank-service
  type: NodePort
  
